version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c 'php artisan serve --host 0.0.0.0 --port 80'
    env_file:
      - .env
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - ./:/var/www/html

  mysql:
    image: 'mysql:8.0'
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - '/var/lib/mysql'
